# Generated by Django 5.1.1 on 2025-03-15 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=303)),
                ('incredients', models.CharField(max_length=303)),
                ('nutrients', models.CharField(max_length=303)),
                ('time', models.CharField(max_length=303)),
                ('amount', models.CharField(max_length=303)),
                ('price', models.IntegerField()),
                ('image', models.FileField(null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.supplier')),
            ],
        ),
    ]
