# Generated by Django 5.1.1 on 2025-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='status',
            field=models.CharField(default='Request Pending', max_length=20, null=True),
        ),
    ]
