# Generated by Django 5.1.1 on 2025-03-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_food_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='CART', max_length=50)),
                ('count', models.IntegerField(default=1)),
                ('cart_date', models.DateTimeField(auto_now_add=True)),
                ('book_date', models.DateTimeField(null=True)),
                ('payment_date', models.DateTimeField(null=True)),
                ('total', models.IntegerField()),
                ('boy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.delivery')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.user')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.food')),
            ],
        ),
    ]
