# Generated by Django 5.1.1 on 2025-03-16 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('goal', models.CharField(max_length=30)),
                ('file', models.FileField(null=True, upload_to='')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.supplier')),
            ],
        ),
    ]
